"""
Wilderness surface zones — one walkable ground-level screen per (zx, zy).

Each zone is a full 80×43 GameMap the player walks around; stepping off an edge
moves to the neighbouring zone (see Engine._try_edge_walk). Town zones are
generated by town_gen/town_gen_procedural instead; this handles only the
wilderness between them.

Seeded deterministically per (seed, zx, zy) so the same seed always yields the
same world. A **walkable-border invariant** keeps the outermost row/column
walkable (grass) so a player arriving on the opposite edge never lands inside an
impassable tile — this also makes the seams between zones visually continuous.
"""
from __future__ import annotations
import random
from typing import TYPE_CHECKING
import tiles as tile_types
import constants as C
from game_map import GameMap

if TYPE_CHECKING:
    from world import World


def _blob(game_map: GameMap, rng: random.Random, tile, count_range, radius_range) -> None:
    for _ in range(rng.randint(*count_range)):
        cx = rng.randint(1, game_map.width - 2)
        cy = rng.randint(1, game_map.height - 2)
        radius = rng.randint(*radius_range)
        for y in range(max(1, cy - radius), min(game_map.height - 1, cy + radius + 1)):
            for x in range(max(1, cx - radius), min(game_map.width - 1, cx + radius + 1)):
                if (x - cx) ** 2 + (y - cy) ** 2 <= radius ** 2 and rng.random() < 0.65:
                    game_map.tiles[y, x] = tile


def generate_surface_zone(world: World, zx: int, zy: int, rng: random.Random) -> GameMap:
    game_map = GameMap(world, C.MAP_WIDTH, C.MAP_HEIGHT)
    game_map.tiles[:, :] = tile_types.FLOOR

    # Keep decorative grass sparse so the default floor dot remains dominant.
    _blob(game_map, rng, tile_types.GRASS, (3, 6), (1, 2))

    # Scatter terrain: forest patches (walkable), plus occasional impassable
    # water and mountains for variety and to make the map read as wilderness.
    _blob(game_map, rng, tile_types.FOREST, (3, 7), (2, 4))
    _blob(game_map, rng, tile_types.WATER, (0, 2), (1, 3))
    _blob(game_map, rng, tile_types.MOUNTAIN, (0, 2), (1, 3))

    # Walkable-border invariant: the outer ring is always plain floor, so an
    # entity arriving on any edge lands on a walkable tile and zones connect.
    game_map.tiles[0, :] = tile_types.FLOOR
    game_map.tiles[game_map.height - 1, :] = tile_types.FLOOR
    game_map.tiles[:, 0] = tile_types.FLOOR
    game_map.tiles[:, game_map.width - 1] = tile_types.FLOOR

    game_map.player_start = (game_map.width // 2, game_map.height // 2)
    return game_map
