from __future__ import annotations


MAP_FLOOR = "map.floor"
MAP_WALL = "map.wall"
MAP_GRASS = "map.grass"
MAP_COBBLESTONE = "map.cobblestone"
MAP_INDOOR_FLOOR = "map.indoor_floor"
MAP_DOOR = "map.door"
MAP_DIRT = "map.dirt"
MAP_DIRT_WET = "map.dirt_wet"
MAP_DOWN_STAIRS = "map.down_stairs"
MAP_UP_STAIRS = "map.up_stairs"
MAP_FOREST = "map.forest"
MAP_TOWN_ENTRANCE = "map.town_entrance"
MAP_WATER = "map.water"
MAP_MOUNTAIN = "map.mountain"

ENTITY_PLAYER = "entity.player"
ENTITY_ORC = "entity.orc"
ENTITY_TROLL = "entity.troll"
ENTITY_VILLAGER = "entity.villager"
ENTITY_WELL = "entity.well"
ENTITY_CARAVAN = "entity.caravan"
ENTITY_HEALTH_POTION = "entity.health_potion"
ENTITY_LIGHTNING_SCROLL = "entity.lightning_scroll"
ENTITY_FIREBALL_SCROLL = "entity.fireball_scroll"
ENTITY_CONFUSION_SCROLL = "entity.confusion_scroll"
ENTITY_CROP_SEED = "entity.crop_seed"
ENTITY_CROP_SPROUT = "entity.crop_sprout"
ENTITY_CROP_GROWING = "entity.crop_growing"
ENTITY_CROP_RIPE = "entity.crop_ripe"
